services:
  nestjs-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: znovandap/wz-nestjs-app-dev:1.0.0
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./src:/app/src
    networks:
      - wz_nestjs_dev
    depends_on:
      - postgres-db-dev
      - redis-dev
    environment:
      - "PORT=${PORT:-3000}"
      - "PREFIX=${PREFIX:-api}"
      - "VERSION=${VERSION:-v1}"
      # Database
      - "DB_HOST=${DB_HOST:-postgres-db-dev}"
      - "DB_PORT=${DB_PORT:-5432}"
      - "DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-wz_nestjs_dev}"
      - "DB_USERNAME=${DB_USERNAME:-wz_nestjs_dev}"
      - "DB_PASSWORD=${DB_PASSWORD:-wz_nestjs_dev}"
      - "DB_NAME=${DB_NAME:-wz_nestjs_dev}"
      - "DB_SYNCHRONIZE=${DB_SYNCHRONIZE:-true}"
      - "DB_LOGGING=${DB_LOGGING:-true}"
      - "DB_DROP_SCHEMA=${DB_DROP_SCHEMA:-true}"
      # Redis
      - "REDIS_HOST=${REDIS_HOST:-redis-dev}"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD:-wz_nestjs_dev}"
      - "REDIS_DB=${REDIS_DB:-0}"
      # Other
      - "JWT_SECRET=b67iccqEd2NzED7EhqSTwzPSmI7dOzDKLpvr5MlZRY"
    
  postgres-db-dev:
    image: postgres:14
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - "POSTGRES_USER=${DB_USERNAME:-wz_nestjs_dev}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-wz_nestjs_dev}"
      - "POSTGRES_DB=${DB_NAME:-wz_nestjs_dev}"
    volumes:
      - wz_nestjs_dev_db:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wz_nestjs_dev
  
  redis-dev:
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-wz_nestjs_dev}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - wz_nestjs_dev
    volumes:
      - wz_nestjs_dev_redis:/data

volumes:
  wz_nestjs_dev_db:
  wz_nestjs_dev_redis:

networks:
  wz_nestjs_dev:
    driver: bridge